### PR TITLE
Issue 85: turbineSensor throws occasional NPE

### LINKED ISSUE #85: turbineSensor throws occasional NPE
I see this message occasionally:
```
java.lang.NullPointerException
        at io.pravega.example.iot.TurbineHeatSensor$SensorReader.run(TurbineHeatSensor.java:445)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**
Fix in `TrubineHeatSensor.java` for avoiding the application to throw `NullPointerException`. Note that this PR only targets this specific problem (i.e., other exceptions or problems will be treated separately).

**Purpose of the change**
Fixes #85.

**What the code does**
The reader (`SensorReader`) is incorrectly interacting with `produceStats` instead of with `consumeStats`. Moreover, the read loop of this class parses read events without checking for null events (e.g., after timeout). The fix consists of replacing reader interactions from `produceStats` to `consumeStats` as well as to check for a null read event before executing the parse logic.

**How to verify it**
Execute the application and verify that it does not throws NPE.

### CODE REVIEW

File: scenarios/turbine-heat-sensor/src/main/java/io/pravega/turbineheatsensor/TurbineHeatSensor.java [hunk 1]
```diff
@@ -438,13 +438,16 @@ public void run() {
...
-                            return CompletableFuture.completedFuture(null);
-                        }, Long.parseLong(result.getEvent().split(",")[0]), 100);
+                        if (result.getEvent() != null) {
+                            consumeStats.runAndRecordTime(() -> {
+                                return CompletableFuture.completedFuture(null);
+                            }, Long.parseLong(result.getEvent().split(",")[0]), 100);
+                            totalEvents--;
+                        }
                     } catch (ReinitializationRequiredException e) {
                         e.printStackTrace();
```
Comment (fpj) [inline scenarios/turbine-heat-sensor/src/main/java/io/pravega/turbineheatsensor/TurbineHeatSensor.java]: Let's create an issue to remove this print stack trace.

Comment (RaulGracia) [reply scenarios/turbine-heat-sensor/src/main/java/io/pravega/turbineheatsensor/TurbineHeatSensor.java]: Ok, I will create it.

Comment (fpj) [reply scenarios/turbine-heat-sensor/src/main/java/io/pravega/turbineheatsensor/TurbineHeatSensor.java]: https://github.com/pravega/pravega-samples/issues/118
